const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getDroppedFilePath: (file) => webUtils.getPathForFile(file),
  preview:         (folder) => ipcRenderer.invoke('preview', folder),
  organize:        (folder) => ipcRenderer.invoke('organize', folder),
  undo:            (moves)  => ipcRenderer.invoke('undo', moves),
  getGroups:       ()       => ipcRenderer.invoke('get-groups'),
  saveGroups:      (g)      => ipcRenderer.invoke('save-groups', g),
  previewGroups:   (folder) => ipcRenderer.invoke('preview-groups', folder),
  organizeGroups:  (folder) => ipcRenderer.invoke('organize-groups', folder),
  getLog:          ()       => ipcRenderer.invoke('get-log'),
  clearLog:        ()       => ipcRenderer.invoke('clear-log'),
  deleteSession:   (id)     => ipcRenderer.invoke('delete-session', id),
  getStats:        ()       => ipcRenderer.invoke('get-stats'),
  getCategories:   ()       => ipcRenderer.invoke('get-categories'),
  saveCategories:  (c)      => ipcRenderer.invoke('save-categories', c),
  resetCategories: ()       => ipcRenderer.invoke('reset-categories'),
  getSettings:     ()       => ipcRenderer.invoke('get-settings'),
  saveSettings:    (s)      => ipcRenderer.invoke('save-settings', s),
  schedule:        (opts)   => ipcRenderer.invoke('schedule', opts),
  unschedule:      ()       => ipcRenderer.invoke('unschedule'),
  pickFolder:      ()       => ipcRenderer.invoke('pick-folder'),
  getDownloads:    ()       => ipcRenderer.invoke('get-downloads'),
  scanDuplicates:    (opts)  => ipcRenderer.invoke('scan-duplicates', opts),
  deleteDuplicates:  (files) => ipcRenderer.invoke('delete-duplicates', files),
  restoreDuplicates: (files) => ipcRenderer.invoke('restore-duplicates', files),
  startWatcher:     (folder) => ipcRenderer.invoke('start-watcher', folder),
  stopWatcher:      ()       => ipcRenderer.invoke('stop-watcher'),
  getWatcherStatus: ()       => ipcRenderer.invoke('get-watcher-status'),
  onWatcherEvent:   (cb)     => { ipcRenderer.removeAllListeners('watcher-event'); ipcRenderer.on('watcher-event', (_, data) => cb(data)); },
  getBookmarks:   ()       => ipcRenderer.invoke('get-bookmarks'),
  addBookmark:    (folder) => ipcRenderer.invoke('add-bookmark', folder),
  removeBookmark: (id)     => ipcRenderer.invoke('remove-bookmark', id),
  minimize:        ()       => ipcRenderer.send('minimize'),
  maximize:        ()       => ipcRenderer.send('maximize'),
  close:           ()       => ipcRenderer.send('close'),
  exportCsv:      (path)    => ipcRenderer.invoke('export-csv', path),
  exportPdf:      (path)    => ipcRenderer.invoke('export-pdf', path),
  showSaveDialog: (opts)    => ipcRenderer.invoke('show-save-dialog', opts),
  scanCleanup:    (opts)   => ipcRenderer.invoke('scan-cleanup', opts),
  runCleanup:     (opts)   => ipcRenderer.invoke('run-cleanup', opts),
  restoreCleanup: (files)  => ipcRenderer.invoke('restore-cleanup', files),
  getRecentFolders: ()       => ipcRenderer.invoke('get-recent-folders'),
  addRecentFolder:  (folder) => ipcRenderer.invoke('add-recent-folder', folder),
  getPathForFile: (filePath) => ipcRenderer.invoke('get-path-for-file', filePath),
  openFileLocation: (filePath) => ipcRenderer.invoke('open-file-location', filePath),
  openFolder:       (folder)   => ipcRenderer.invoke('open-folder', folder),
  undoSingleFile:   (opts)     => ipcRenderer.invoke('undo-single-file', opts),
  recategorizeFile: (opts) => ipcRenderer.invoke('recategorize-file', opts),
  getAppVersion:    ()       => ipcRenderer.invoke('get-app-version'),
  checkForUpdates:  ()       => ipcRenderer.invoke('check-for-updates'),
  openReleasePage:  (url)    => ipcRenderer.invoke('open-release-page', url),
  onUpdateAvailable: (cb)    => { ipcRenderer.removeAllListeners('update-available'); ipcRenderer.on('update-available', (_, data) => cb(data)); },
  filePreview:      (p)      => ipcRenderer.invoke('file-preview', p),
  getIgnoreList:    ()       => ipcRenderer.invoke('get-ignore-list'),
  saveIgnoreList:   (l)      => ipcRenderer.invoke('save-ignore-list', l),
  resetIgnoreList:  ()       => ipcRenderer.invoke('reset-ignore-list'),
  scheduleCleanup:  (opts)   => ipcRenderer.invoke('schedule-cleanup', opts),
  unscheduleCleanup: ()      => ipcRenderer.invoke('unschedule-cleanup'),
  getRenameRules:   ()       => ipcRenderer.invoke('get-settings').then(s => s.renameRules || {}),
  saveRenameRules:  (rules)  => ipcRenderer.invoke('get-settings').then(async s => { s.renameRules = rules; return ipcRenderer.invoke('save-settings', s); }),
  getRules:         ()       => ipcRenderer.invoke('get-rules'),
  saveRules:        (rules)  => ipcRenderer.invoke('save-rules', rules),
  runRules:         (opts)   => ipcRenderer.invoke('run-rules', opts),
  exportAppData:    ()       => ipcRenderer.invoke('export-app-data'),
  importAppData:    ()       => ipcRenderer.invoke('import-app-data'),
  exportGroups:     ()       => ipcRenderer.invoke('export-groups'),
  importGroups:     ()       => ipcRenderer.invoke('import-groups'),
  getRecycleBinSize: ()      => ipcRenderer.invoke('get-recycle-bin-size'),
  emptyRecycleBin:   ()      => ipcRenderer.invoke('empty-recycle-bin'),
  registerContextMenu:   ()  => ipcRenderer.invoke('register-context-menu'),
  unregisterContextMenu: ()  => ipcRenderer.invoke('unregister-context-menu'),
  onContextMenuOrganize: (cb) => { ipcRenderer.removeAllListeners('context-menu-organize'); ipcRenderer.on('context-menu-organize', (_, folder) => cb(folder)); },
  onTrayAction: (cb) => { ipcRenderer.removeAllListeners('tray-action'); ipcRenderer.on('tray-action', (_, data) => cb(data)); },
  downloadUpdate: () => ipcRenderer.invoke('download-update'),
  installUpdate:  () => ipcRenderer.invoke('install-update'),
  onUpdaterStatus: (cb) => { ipcRenderer.removeAllListeners('updater-status'); ipcRenderer.on('updater-status', (_, data) => cb(data)); },
  
});
